spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: user-registration-service
    description: This service is used for user management and registration
    version: 0.0.1-SNAPSHOT
server:
  port: 8082